### ISSUE TITLE
left click menu requires held mouse button

### ISSUE THREAD

**Issue by AladW** [tbursztyka/connman-ui#14]
To get the right click menu, one right click is enough to keep the menu open. The left click menu however requires the left mouse button to be held. I'm using connman-ui with xfce4-panel 4.10.1. Simply curious if this is intended behaviour or not.

**Comment by tbursztyka** [comment]
This behavior is the default one from Xfce's systray. But I guess there is a way to prevent that, from connman-ui's code. 

Would you be willing to investigate?

**Comment by AladW** [comment]
FWIW, it's the same with i3wm. When I run connman-ui-gtk from the terminal, and left-click, I get this error message:

(connman-ui-gtk:11415): GLib-CRITICAL **: Source ID 891 was not found when attempting to remove it

on GTK 3.14.8

**Comment by tbursztyka** [comment]
This source id warning is not related to the menu behavior, which is nominal btw. I verified, and a left click menu is supposed to be like that on any systray.

The source id thing on the other hand would need some investigation. Though it is not that critical.

Closing since the behavior is fine.

**Comment by matsaman** [comment]
Left-click isn't like that with nm-applet, which is what connman-ui is mostly potentially replacing, I dare say. Would be great if this could be fixed.

**Comment by tbursztyka** [comment]
I don't maintain connman-ui anymore (though it still "works"). Please move towards: 
https://github.com/jgke/connman-gtk

Which is way better in all aspects.
