### ISSUE TITLE
Display Available Networks issue: Pop up box does not expand with systray on bottom panel

### ISSUE THREAD

**Issue by pete4abw** [tbursztyka/connman-ui#15]
System and Platform:
--------------------------
KDE=4.10.5 (fresh home .kde folder)
Kernel: 3.10.17 (stock)
OS: Slackware 14.1 (stock)
Video: nouveau driver (VGA compatible controller: NVIDIA Corporation GF108M [GeForce GT 540M] (rev a1))
Git Pull: 2015-02-15

Description of issue:
-------------------------
With system tray on bottom panel, left-clicking connman-ui icon brings up an unusable list of available networks. All that's visible is scroll arrows at top and bottom.

With system tray on top panel, display of available networks works fine.

Thank you.

![connman-ui-gtk-connections-bot](https://cloud.githubusercontent.com/assets/10359685/6427063/123085ae-bf2a-11e4-9f3d-a23f92731b65.png)
![connman-ui-gtk-connections-top](https://cloud.githubusercontent.com/assets/10359685/6427065/15ec9a3e-bf2a-11e4-8252-67665e0a33a5.png)

**Comment by tbursztyka** [comment]
That's a known Gtk+ issue (check this: https://github.com/tbursztyka/connman-ui/issues/6 )

However there is something new in your case: it seems to work when the panel is on top of the screen.
Never got that working myself on kde systray. So it means gtk is doing things a bit better this time somehow.

**Comment by pete4abw** [comment]
Apologies for dup.

**Comment by pete4abw** [comment]
Update. Right click menu (Airplane mode, On and Off toggles) always expands menu to full height. Maybe because it is fixed size, not growable. However, some times (not always) click-hold iteratively causes the menu to grow each time. In addition, if system tray is on top and menu viewed then moved to the bottom, menu expands properly the first time. Obviously a defect in gtk, but maybe this is helpful.
![connman-ui_rightclickmenu](https://cloud.githubusercontent.com/assets/10359685/6576353/d73bd6b6-c6f3-11e4-9117-1410a9bec74d.png)

**Comment by timothytylee** [comment]
This issue can be fixed with pull request #18

**Comment by tbursztyka** [comment]
@timothytylee : Would you mind fixing the menu position issue? Looks like it has been introduced by your patch. Don't get me wrong, your patch is nice. Actually, this is again a proof that gtk does really stupid stuff around systray.

The fix would be to store the position at the left click on the systray icon. Then for every update of the menu: requesting the same position.

**Comment by timothytylee** [comment]
Dear Tomasz,

I've written up a patch and created a pull request.  The fix uses a 
callback function to position the popup menu.  Code copied from 
gtk_position_menu() to override the anchor position and menu size 
calculation.

You're right about GTK not doing enough about the system tray side of 
thing...... :(

Regards,
Timothy

**Comment by tbursztyka** [comment]
Thanks a lot!

I'll try to find some time to review it, test it and merge it.

**Comment by tbursztyka** [comment]
Patch merged, thanks Timothy.

Btw, have you noticed that now systray icon on Gtk is a "deprecated feature"? (and only because gnome does not need it... because of course only gnome uses gtk...)

**Comment by timothytylee** [comment]
Dear Tomasz,

I noticed that during compilation.  I hope they don't decide to pull the 
support for GtkStatusIcon completely... :(

Regards,
Timothy
