### ISSUE TITLE
Left-button menu changes its position depending on cursor

### ISSUE THREAD

**Issue by jqrsd** [tbursztyka/connman-ui#21]
If tray is located at the bottom, left-button menu arises below the screen. When mouse cursor is out of menu, it can jump somewhere, making selection of required network quite annoying.

**Comment by jqrsd** [comment]
It doesn't duplicate #15: the bug in the title appears with upper tray too.

**Comment by tbursztyka** [comment]
It's a bug introduced by latest patch, the one that fixes the menu size calculation (this which should be done by gtk which is completely bogus around systray when you compare with qt).

**Comment by tbursztyka** [comment]
Patch merged, thanks Timothy
