### ISSUE TITLE
new fresher for connman-ui for embeded system

### ISSUE THREAD

**Issue by ShiyuanSolutions** [tbursztyka/connman-ui#29]
hello master, i download the connman-ui packets for "connmand project",and it run as follows,
** (connman-ui-gtk:16251): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

although,it is a warning, i still want to know why it is? 
and then ,why not pop up connman-ui user interface on my ubuntu desktop,any problems occurred?

**Comment by tbursztyka** [comment]
Hello, please switch to connman-gtk ( https://github.com/jgke/connman-gtk ) which is full-featured etc...
connman-ui is not maintained anymore.
