### ISSUE TITLE
applet menu blinks

### ISSUE THREAD

**Issue by sacredshit** [tbursztyka/connman-ui#30]
[I made a thread in the Archlinux subreddit](https://www.reddit.com/r/archlinux/comments/8kbhdf/connman_applet_blinks/)
I installed connman-ui-git from the AUR, I couldn't get hold of the menu to select my wifi network. I had to hold down the button in my trackpad and tap with my other finger to select a network(while still holding down the button, I had to make multiple attempts).

**Comment by tbursztyka** [comment]
Hi,

Menu behaviour depends on the WM, if I am not mistaken. Anyway I don't maintain this project anymore.

Could you switch to https://github.com/jgke/connman-gtk instead? It's way better, with more features, nicer UI and it's still maintained :)

**Comment by sacredshit** [comment]
Thanks for the reply, I just switched to connman-gtk and it's good! Thanks :)
